### ISSUE TITLE
C'est quoi AGIMUS?

### ISSUE THREAD

**Issue by Snownamida** [EsupPortail/cas-server-support-agimus-cookie#7]
Juste une question, c'est quoi exactement AGIMUS?
j'ai trouvé un cookie AGIMUS dans la page d'authentification de mon école, mais quand je fais la cherche, j'ai trouvé AGIMUS est d'un projet du robot et n'a rien à voir avec cookie.

**Comment by marchal-julien** [comment]
Bonjour !

Vous trouverez de l'information sur le projet agimus sur cette page : 
https://www.esup-portail.org/wiki/display/AGIMUSNG/Documentations
Cordialement,

**Comment by Snownamida** [comment]
D'accord, merci beaucoup !!
